name: Reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: Name of artifact to be deployed
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: Reusable workflow output
                value: ${{ jobs.deploy.outputs.outcome }}
jobs:
    deploy:
        outputs:
            outcome: ${{steps.result.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Deploy
              run: echo 'Deploying from reusable workflow'
            - name: Output
              id: result
              run: echo "step-result=success" >> $FITHUB_OUTPUT
